import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import home from '../styles/Home.css'
import Menu from '../components/Menu'
import linkname from '../data/linkname'
import twitterName from '../data/twitterlink'
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>self-introduction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header open={"none"}/>
      <div className={home.first}>
        <figure className="rounded-circle">
          <Image
              src='/img/me.jpg'
              height={150}
              width={150}
              alt='logo'
              className={home.img2}
          />
        </figure>
        <p className={home.p}>
          はじめまして。TERUSIです。
          このサイトは私の自己紹介サイトになります。
        </p>
      </div>
      <div className="container text-center">
        <h1>menu</h1>
        <Menu name={linkname} detail={''}/>  
        <h1 >contact</h1>
        <Menu name={twitterName} detail={'連絡の際はどちらのアカウントでも構いません。'}/>
      </div>
    </>
  )
}

export default Home
