import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from './components/Header'
import Profile from './components/Profile'
import Skils from './components/Skils'
const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Myportfolia</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Profile/>
      <Skils/>
    </>
  )
}

export default Home
