import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import Profile from '../components/Profile'

const profile: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Profile/>
    </div>
  )
}

export default profile
