import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import skils from '../styles/skils.css'
import { Skil } from '../data/skildata'
import Image from 'next/image'
import Back from '../components/Back'
import Menucard from './Menucard';
import { Card, Typography } from '@mui/material'
import CardMedia from '@mui/material/CardMedia';
import { motion } from 'framer-motion'

const skil: NextPage = () => {
  return (
    <div>
      <Head>
        <title>myskils</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header open={"flex"}/>
      <Menucard title='言語とツール(ほんの少しでも触ったものも含む)' marginSize={true}>
        {Skil.map((item,index)=>(
            <motion.div 
            key={index} 
            className="d-inline-block m-4"
            layoutId={String(index)}
            >
              <Card sx={{height:780,width:200}} className="text-start">
                <CardMedia
                  sx={{height:200}}
                  image={item.link}
                  title={item.langage}
                />
                <Typography gutterBottom variant="h4" component="div">
                  {item.langage}
                </Typography>
                <Typography gutterBottom variant="h5" component="div">
                  {item.level}
                </Typography>
              </Card> 
            </motion.div>
        ))}
    </Menucard>
      
    </div>
  )
}

export default skil
