import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import skils from '../styles/skils.css'
import { Skil } from '../data/skildata'
import Image from 'next/image'
import Back from '../components/Back'
const skil: NextPage = () => {
  return (
    <div>
      <Head>
        <title>myskils</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header open={"flex"}/>
      <div className={skils.content} id="intro">
        
        <h1>言語とツール(ほんの少しでも触ったものも含む)</h1>
        {Skil.map((item,index)=>(
          <div key={index} className={skils.box}>
            <figure>
              <Image
                src={item.link}
                alt='logo'
                width={50}
                height={50}
                className={skils.img}
              />
            </figure>
            <h2>{item.langage}</h2>
            <p>{item.level}</p>
          </div>
        ))}
     </div>
    </div>
  )
}

export default skil
