import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import { best, goal, goaldata, mybest } from '../data/pbdata'
import { Card, Paper, styled, Table, TableBody, TableCell, tableCellClasses, TableContainer, TableHead, TableRow, Typography } from '@mui/material'
import Menucard from '../components/Menucard'
import { motion } from 'framer-motion'
import { useState } from 'react'
import Animate from '../components/Animate'
//table装飾のための設定
const StyledTableCell = styled(TableCell)(({ theme }) => ({
  [`&.${tableCellClasses.head}`]: {
    backgroundColor: theme.palette.common.black,
    color: theme.palette.common.white,
  },
  [`&.${tableCellClasses.body}`]: {
    fontSize: 21,
  },
}));

const Run: NextPage = () => {
  const [selectId,setSelectId]=useState<string|null>(null);
  const [editModalIsOpen, setEditModalIsOpen] = useState<boolean>(false);
  const openmodal=(id:string)=>{
    setSelectId(id);
    setEditModalIsOpen(true);
  }
  return (
    <>
      <Head>
        <title>running</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header open={"flex"}/>
      <div 
        className="container text-center w-80"
        style={{
          marginTop:"200px",
        }}
      >
        <h1>ランニングについて</h1>
        <p>
          私は高校、大学の部活動で陸上競技の長距離種目
          をやってきました。
        </p>
        <div>
          <h2>自己ベスト</h2>
          <TableContainer component={Paper}>
            <Table aria-label="customized table">
              <TableHead>
                <TableRow>
                  <StyledTableCell align='center'>Event</StyledTableCell>
                  <StyledTableCell align='center'>Personal Best</StyledTableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {mybest.map((item:best,index:number)=>(
                  <TableRow key={index}>
                    <StyledTableCell align='center'>{item.distance}</StyledTableCell>
                    <StyledTableCell align='center'>{item.time}</StyledTableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </div>
        <div
          style={{marginBottom:"40px",marginTop:"10px"}}
        >
          <Menucard title='目標' marginSize={false}>
            {goal.map((item:goaldata,index:number)=>(
              <motion.div
                key={index}
                className="d-inline-block m-4"
                layoutId={String(index)}
                onClick={()=>openmodal(String(index))}
              >
                <Card sx={{height:100,width:200}}  className="text-center d-inline-block m-3">
                  <Typography gutterBottom variant="h4" component="div" >
                    {item.goal}
                  </Typography>
                </Card>
              </motion.div>
            ))}
            <Animate
              selectId={selectId}
              editModalIsOpen={editModalIsOpen}
              setSelectId={setSelectId}
              setEditModalIsOpen={setEditModalIsOpen}
            >
              <Typography gutterBottom variant="h4" component="div">
                {goal[Number(selectId)].goal}
              </Typography>
              <Typography gutterBottom variant="h5" component="div">
                {goal[Number(selectId)].detail}
              </Typography>
            </Animate>
          </Menucard>
        </div>
      </div>
      
    </>
  )
}

export default Run
