import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/Header'
import home from '../styles/Home.css'
import Link from 'next/link';
import run from '../components/styles/running.css';
import Running from '../components/Runnig'

const Run: NextPage = () => {
  
  return (
    <>
      <Head>
        <title>running</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Running/>
      
    </>
  )
}

export default Run
